---
apiVersion: v1
data:
  start.sh: |-
    #!/bin/sh
    echo "Running script"
kind: ConfigMap
metadata:
  name: startup-script
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: kk-pod3
spec:
  containers:
    - name: app
      image: alpine:3.19
      command: ["/scripts/start.sh"]
      volumeMounts:
        - name: script-vol
          mountPath: /scripts
  volumes:
    - name: script-vol
      configMap:
        name: startup-script
